[project]
name = "manimations"
version = "0.1.0"
description = "python code examples using manim for personal and educational purposes"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "manim>=0.19.0",
]
